[package]
name = "r_reset"
version = "0.1.0"
authors = ["maurice"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_gpiozero =  "0.2.0"
clap = "~2.33"
